apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-workload-config
  namespace: {{ .Values.namespace }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile }}
