apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.services.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  rules:
  - http:
      paths:
      - path: /products
        backend:
          serviceName: {{ .Values.services.productApi.serviceName }}
          servicePort: {{ .Values.services.productApi.port }}
      - path: /orders
        backend:
          serviceName: {{ .Values.services.orderApi.serviceName }}
          servicePort: {{ .Values.services.orderApi.port }}
